-- LU: ActiveSeparete
-- Table: ACTIVE_WORK_ORDER_TAB
-- Campos: WORK_TYPE_ID - Novos Objetos foram criados
-- Ação: NEW:WORK_TYPE_ID = TRANS

DECLARE

ACCESS_GROUP_ VARCHAR(3200);

CURSOR GET_ACCESS_GROUP IS
  SELECT 1
    FROM IFSLAF.USER_GROUP_USER UGU
   INNER JOIN IFSLAF.USER_GROUP UG
      ON UGU.USER_GROUP_ID = UG.USER_GROUP_ID
   WHERE UG.NAME = 'MNT-TRANS' AND
   UGU.USER_ID IN (SELECT FND_USER FROM IFSLAF.FND_SESSION);

BEGIN

OPEN GET_ACCESS_GROUP;
FETCH GET_ACCESS_GROUP INTO ACCESS_GROUP_;
CLOSE GET_ACCESS_GROUP;


 IF ACCESS_GROUP_ IS NULL THEN
  
    RAISE_APPLICATION_ERROR(-20100,
                            'Seu usuário não possíu acesso para criar O.S. de transformação');
  
  END IF;

END;
