DECLARE

BEGIN


IF '&NEW:CF$_PCP_DATE'  <> '&NEW:CF$_FIRST_DATE_PCP'  THEN
   IF '&NEW:CF$_RESCHEDULING_PCP_REASO' IS NULL THEN 
     RAISE_APPLICATION_ERROR(-20100,'PARA REALIZAR REAGENDAMENTO O MOTIVO NÃO PODE ESTÁ EM BRANCO, FAVOR PREENCHER O MOTIVO DO REAGENDAMENTO!');

     END IF;

END IF;

END;