-- LU: DocIssue VIEW: DOC_ISSUE_TAB
-- Campos: Doc_Class , Doc_Resp_Sign
-- Novos documentos

DECLARE

USER_ALLOWED_CLASS_ VARCHAR(100);

CURSOR GET_ALLOWED_CLASS IS
SELECT EDIT_ACCESS
    FROM IFSLAF.DOCUMENT_ACCESS_TEMPLATE
   where GROUP_ID IN (SELECT GROUP_ID
                        FROM IFSLAF.DOCUMENT_GROUP_MEMBERS
                       WHERE PERSON_ID = '&NEW:DOC_RESP_SIGN')
     AND DOC_CLASS = 'ESG'
ORDER BY EDIT_ACCESS DESC;

BEGIN

OPEN GET_ALLOWED_CLASS;
FETCH GET_ALLOWED_CLASS INTO USER_ALLOWED_CLASS_;
CLOSE GET_ALLOWED_CLASS;

IF USER_ALLOWED_CLASS_ != 1 THEN
  
  RAISE_APPLICATION_ERROR(-20100, 'LAF_SGI_001: Você não pode salvar documentos na classe SGI, está classe é reservada'|| USER_ALLOWED_CLASS_);

END IF;

END;