DECLARE

STATUS VARCHAR2(3200) := NULL;


BEGIN

SELECT STATE
INTO RESPOSTA_ANALISE_DE_CREDITO_
FROM ORDER_QUOTATION
WHERE QUOTATION_NO =&NEW:QUOTATION_NO;

IF STATUS ='Liberado' THEN

RAISE_APPLICATION_ERROR(-20100,'LAF_COM_017: Não é possível alterar o preço no status Liberado!');

END IF;

EXCEPTION WHEN NO_DATA_FOUND THEN 
BEGIN

dbms_output.put_line('Dados não encontrados');

END;

END;