DECLARE

  TYPE_FIELD1_ VARCHAR2(10);
  TYPE_FIELD2_ VARCHAR2(10);
  P1_48_       VARCHAR(48); -- DIMESÃO DE CARACTERES NO PAYMENT &NEW:PAYMENT_INFO1 COMEÇANDO COM DIGITO 8 = 48 CARACTERES
  P2_48_       VARCHAR(48); -- DIMESÃO DE CARACTERES NO PAYMENT &NEW:PAYMENT_INFO2 COMEÇANDO COM DIGITO 8 = 48 CARACTERES
  P2_47_       VARCHAR(47); -- DIMESÃO DE CARACTERES NO PAYMENT INFO 2 NÃO COMEÇANDO COM DIGITO 8 = 47 CARACTERES
  P1_44_       VARCHAR(44); -- DIMESÃO DE CARACTERES NO PAYMENT INFO 1 NÃO COMEÇANDO COM DIGITO 8 = 44 CARACTERES

  -- DETERMINANDO TIPO DE CARACTERES INSERIDOS NO PAYMENT INFO

  CURSOR GET_TYPE_FIELD1 IS
    SELECT case
             when trim(TRANSLATE('&NEW:PAYMENT_INFO1', '0123456789', ' ')) is not null then
              'alpha'
             when '&NEW:PAYMENT_INFO1' is null then
              'vazio'
             else
              'numeric'
           end
      FROM DUAL;

  CURSOR GET_TYPE_FIELD2 IS
  
    SELECT case
             when trim(TRANSLATE('&NEW:PAYMENT_INFO2', '0123456789', ' ')) is not null then
              'alpha'
             when '&NEW:PAYMENT_INFO2' is null then
              'vazio'
             else
              'numeric'
           end
      FROM DUAL;

  -- FIM TIPO DE CARACTERE NO PAYMENTE INFO

  -- VERIFICAR SE O CAMPO PAYMENT INFO COMECA DIGITO 8 PAYMENT_&NEW:PAYMENT_INFO1

  CURSOR GET_P1_48 IS
    SELECT 1
      FROM DUAL
     WHERE '&NEW:PAYMENT_INFO1' LIKE '8%'
       AND length('&NEW:PAYMENT_INFO1') = 48;

  -- FIM DE VERIFICACAO DE VARIÁVEL COMEÇANDO COM CARACTER 8 PAYMENT_&NEW:PAYMENT_INFO1

  -- VERIFICAR SE O CAMPO PAYMENT INFO COMECA DIGITO 8 PAYMENT_&NEW:PAYMENT_INFO2

  CURSOR GET_P2_48 IS
    SELECT 1
      FROM DUAL
     WHERE '&NEW:PAYMENT_INFO2' LIKE '8%'
       AND length('&NEW:PAYMENT_INFO2') = 48;

  -- FIM DE VERIFICACAO DE VARIÁVEL COMEÇANDO COM CARACTER 8 PAYMENT_&NEW:PAYMENT_INFO2

  -- VERIFICAR SE O CAMPO PAYMENT INFO 2 POSSUI 47 DIGITOS

  CURSOR GET_P2_47 IS
    SELECT 1
      FROM DUAL
     WHERE LENGTH('&NEW:PAYMENT_INFO2') = 47;

  -- FIM DE VERIFICACAO DE 47 DIGITOS NO PAYMENT INFO 2

  -- VERIFICAR DIMENSAO DE 44 DIGITOS NO PAYMENT INFO 1

  CURSOR GET_P1_44 IS
    SELECT 1
      FROM DUAL
     WHERE LENGTH('&NEW:PAYMENT_INFO1') =44;

  -- FIM DE VERIFICACAO DE 44 DIGITOS NO PAYMENT INFOR 1

BEGIN

  -- CURSOR TYPE_FIELD1

  OPEN GET_TYPE_FIELD1;
  FETCH GET_TYPE_FIELD1
    INTO TYPE_FIELD1_;
  CLOSE GET_TYPE_FIELD1;

  -- FIM DO CURSOR TYPE_FIELD1

  -- CURSOR TYPE_FIELD2

  OPEN GET_TYPE_FIELD2;
  FETCH GET_TYPE_FIELD2
    INTO TYPE_FIELD2_;
  CLOSE GET_TYPE_FIELD2;

  -- FIM DO CURSOR TYPE_FIELD2

  -- CURSOR P1_48 PAYMENT_&NEW:PAYMENT_INFO1 COMEÇA COM 8 E TEM 48 CARACTERES

  OPEN GET_P1_48;
  FETCH GET_P1_48
    INTO P1_48_;
  CLOSE GET_P1_48;

  -- FIM DO CURSOR  P1_48 PAYMENT_&NEW:PAYMENT_INFO1 

  -- CURSOR P2_48 PAYMENT_&NEW:PAYMENT_INFO2 COMEÇA COM 8 E TEM 48 CARACTERES

  OPEN GET_P2_48;
  FETCH GET_P2_48
    INTO P2_48_;
  CLOSE GET_P2_48;

  -- FIM DO CURSOR  P2_48 PAYMENT_&NEW:PAYMENT_INFO2

  -- CURSOR P2_47 PAYMENT_&NEW:PAYMENT_INFO2 47 CARACTERES

  OPEN GET_P2_47;
  FETCH GET_P2_47
    INTO P2_47_;
  CLOSE GET_P2_47;

  -- FIM DO CURSOR  P2_47 PAYMENT_&NEW:PAYMENT_INFO2

  -- CURSOR P1_44 PAYMENT_&NEW:PAYMENT_INFO1 44 CARACTERES

  OPEN GET_P1_44;
  FETCH GET_P1_44
    INTO P1_44_;
  CLOSE GET_P1_44;

  -- FIM DO CURSOR  P1_44 PAYMENT_&NEW:PAYMENT_INFO1

  -- CONDICOES PARA TRATATIVA DAS VARIAVEIS

  IF '&NEW:PARTY_TYPE' = 'SUPPLIER' THEN
    -- VERIFICA SE A REQUISIÇÃO ESTA VINDO DO SISTEMA OU DO USUÁRIO
  
    IF TYPE_FIELD1_ = 'alpha' OR TYPE_FIELD2_ = 'alpha' THEN
      -- SE VALOR PASSADO NA VARIAVEL FOR ALPHA SERA EXIBIDO O ERRO 
    
      RAISE_APPLICATION_ERROR(-20100, 'O valor inserido não é numérico');

    ELSE

      -- SE VALOR ENCONTRATO NUMERICO VERIFICAREMOS A QUANTIDADE DE CARACTERES
       IF P1_48_ IS NULL AND P2_48_ IS NULL AND P2_47_ IS NULL AND P1_44_ IS NULL THEN
        ---AND P2_47_ AND P1_44 VERIFICA SE ALGUMA DAS VARIAVEIS E NÃO FOR NULA, SE ALGUMA NAO FOR NULA SIGNIFICA QUE ATENDEU OS REQUISITOS DE CODIGO DE BARRA E ESTA CORRETA ESTAO FARA
     
        RAISE_APPLICATION_ERROR(-20100,
                                'A quantidade de caracteres no campo inserido não conincide com o padrão, ( Payment_2: 47 digitos, Payment1: aceita 44 dígitos, Se começa com dígito 8: 48 caracteres ambos )');
      
        -- ELSE IF -- SE TODAS AS VARIAVEIS FOREM NULAS, SIGNIFICA QUE OS CAMPOS DE PAYMENT_INFO FORAM PRENECHIDOS DE FORMA INCORRETA, SERA EXIBIDO O ERRO ABAIXO
      
      END IF;
    
    END IF;
  END IF;

END;