-- LU: CustomerInfo
-- Table: CUSTOMER_INFO_TAB
-- Campos: CUSTOMER_ID
-- Acionamentos: NEW 

DECLARE

IDCLIENTE_ VARCHAR2(11) := NULL;

CURSOR IDCLIENTE IS
SELECT 1
FROM DUAL
WHERE LENGTH('&NEW:CUSTOMER_ID') = 8 OR LENGTH('&NEW:CUSTOMER_ID') = 11;

BEGIN

OPEN IDCLIENTE;
FETCH IDCLIENTE INTO IDCLIENTE_;
CLOSE IDCLIENTE;


IF IDCLIENTE_ IS NULL THEN
RAISE_APPLICATION_ERROR(-20100,'ID Cliente fora do Padrão');
END IF;

END;